HBASE-21674:Port HBASE-21652 (Refactor ThriftServer making thrift2 server inherited from thrift1 server) to branch-1
apache/hbase pull request #2941
Opened 2021-02-08 13:53 UTC by YutSean

https://issues.apache.org/jira/browse/HBASE-21674
The admin operations of Thrift2 are not implement. They will be implemented in the future.

2021-02-08 14:58 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m 50s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  2s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 44s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 56s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  9s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  0s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 54s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 54s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 40s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 59s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 58s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 46s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 46s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 56s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 33s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 64 unchanged - 38 fixed = 105 total (was 102)  |
| -1 :x: |  checkstyle  |   0m 28s |  hbase-common: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  checkstyle  |   0m 46s |  hbase-thrift: The patch generated 354 new + 83 unchanged - 76 fixed = 437 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 53s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m 17s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 41s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  findbugs  |   2m  8s |  hbase-thrift generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 47s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  The patch does not generate ASF License warnings.  |
|  |   |  64m 22s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-thrift |
|  |  The class name org.apache.hadoop.hbase.thrift2.ThriftServer shadows the simple name of the superclass org.apache.hadoop.hbase.thrift.ThriftServer  At ThriftServer.java:the simple name of the superclass org.apache.hadoop.hbase.thrift.ThriftServer  At ThriftServer.java:[lines 52-113] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 3e09fc865abd 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / 7d80d99 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/diff-checkstyle-hbase-common.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/diff-checkstyle-hbase-thrift.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| findbugs | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/new-findbugs-hbase-thrift.html |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/testReport/ |
| Max. process+thread count | 133 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-02-08 20:27 UTC, saintstack reviewed
I skimmed the change. Looks ok. What sort of testing have  you done? Can you fix the checkstyle, etc., complaints? If in generated code, you won't be able to so just call them out as so. What about the unit test failures? Thanks.

2021-02-09 02:55 UTC, YutSean commented
I fixed the code style and the unit test failure results from the wrong version of Java.

2021-02-09 03:47 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 13s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 26s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 11s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 43s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 57s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 10s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  4s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 47s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 39s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 58s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 45s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 57s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 34s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 64 unchanged - 38 fixed = 105 total (was 102)  |
| -1 :x: |  checkstyle  |   0m 28s |  hbase-common: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  checkstyle  |   0m 35s |  hbase-thrift: The patch generated 14 new + 82 unchanged - 77 fixed = 96 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 48s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 40s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  findbugs  |   2m  8s |  hbase-thrift generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 43s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  52m 42s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-thrift |
|  |  The class name org.apache.hadoop.hbase.thrift2.ThriftServer shadows the simple name of the superclass org.apache.hadoop.hbase.thrift.ThriftServer  At ThriftServer.java:the simple name of the superclass org.apache.hadoop.hbase.thrift.ThriftServer  At ThriftServer.java:[lines 52-113] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux ebfeccd45f4a 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / 7d80d99 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/diff-checkstyle-hbase-common.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/diff-checkstyle-hbase-thrift.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| findbugs | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/new-findbugs-hbase-thrift.html |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/testReport/ |
| Max. process+thread count | 181 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-02-09 04:01 UTC, YutSean commented
While we update the thrift version from 0.98 to 0.13.0, which needs java version at least 52, this will lead to the javadoc failures. Have no idea how to solve this.

2021-02-09 04:52 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  1s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  4s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 45s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  9s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  1s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 52s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 39s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 59s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 46s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 46s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 57s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 33s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 64 unchanged - 38 fixed = 105 total (was 102)  |
| +1 :green_heart: |  checkstyle  |   0m 28s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 52s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 30s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 40s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 18s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 43s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  52m 35s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 9a4aafa173c5 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / 7d80d99 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/3/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/3/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/3/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/3/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/3/testReport/ |
| Max. process+thread count | 112 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-02-09 05:19 UTC, saintstack commented
> While we update the thrift version from 0.98 to 0.13.0, which needs java version at least 52, this will lead to the javadoc failures

Where does the update from 0.98 thrift to 0.13 happen? It is not in this patch. This backport is compiled w/ java 1.7. What version is that? Is it 52 or 51? Thanks.

2021-02-09 05:46 UTC, YutSean commented
I find the problem. I compile the thrift file locally with java 8, so that the generated code cannot pass the check. I have regenerated the code with java 7.

2021-02-09 06:41 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 13s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  1s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 57s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 43s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  8s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  1s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 48s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  1s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 46s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 46s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 58s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 35s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 64 unchanged - 38 fixed = 105 total (was 102)  |
| +1 :green_heart: |  checkstyle  |   0m 30s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 45s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 37s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 17s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 57s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 34s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  52m 30s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 1a966ed59632 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / 7d80d99 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/4/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/4/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/4/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/4/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/4/testReport/ |
| Max. process+thread count | 181 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/4/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-02-09 07:14 UTC, YutSean commented
I checked branch-1 already uses thrift 0.13.0

2021-02-09 08:35 UTC, Reidddddd commented
ping @apurtell @busbey 
> major version 52 is newer than 51, the highest major version supported by this compiler. It is recommended that the compiler be upgraded.

is it expected since we are using jdk 7?

2021-02-17 02:26 UTC, Reidddddd approved these changes
Spared some time to take a full review, LGTM.
But not sure the complaints..

2021-03-15 07:52 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  12m 16s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  3s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 30s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 48s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 58s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 11s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  5s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 41s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  0s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 46s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 46s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 59s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 36s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 64 unchanged - 38 fixed = 105 total (was 102)  |
| +1 :green_heart: |  checkstyle  |   0m 28s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  shadedjars  |   2m 52s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 49s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 30s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 42s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 15s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 57s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 39s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  64m 56s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 906bb8c74e7e 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / ba80103 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/artifact/out/whitespace-eol.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/testReport/ |
| Max. process+thread count | 181 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/5/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-03-17 02:25 UTC, YutSean commented
@saintstack @Reidddddd The problem is still there.

2021-03-18 19:24 UTC, saintstack commented
Is the complaint that thrift 0.13 has been compiled w/ jdk8?

There is white space complaints, the javadoc WARNINGs we can ignore since they are in generated code, can you figure the thrift unit test failure?

Thanks.

2021-04-01 02:05 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m 10s |  https://github.com/apache/hbase/pull/2941 does not apply to branch-1. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/6/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-04-01 03:17 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  12m 53s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 19s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 45s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 56s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  9s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  3s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 51s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 40s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  0s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 47s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 58s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 35s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 64 unchanged - 38 fixed = 105 total (was 102)  |
| +1 :green_heart: |  checkstyle  |   0m 30s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 51s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 50s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 41s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 18s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 45s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  The patch does not generate ASF License warnings.  |
|  |   |  65m  7s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 542e07c495b5 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / d07ef8f |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/7/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/7/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/7/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/7/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/7/testReport/ |
| Max. process+thread count | 166 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/7/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-04-01 03:25 UTC, YutSean commented
Right, the complaint means the thrift 0.13 package is complied by java 8. The whitespace is just for triggering the QA. The unit tests also report the java version problem of thrift 0.13.

2021-04-01 03:26 UTC, YutSean commented
I have removed the redundant whitespace and trigger the QA again.

2021-06-14 15:13 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  14m 25s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  1s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 29s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 10s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 49s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 58s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 16s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 20s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 54s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m  9s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 45s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 10s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  0s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 47s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 59s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 35s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 66 unchanged - 38 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 30s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| -1 :x: |  shadedjars  |   0m 14s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 45s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 28s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 54s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 26s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 38s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 34s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  The patch does not generate ASF License warnings.  |
|  |   |  61m 30s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 304863b4ba81 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/whitespace-eol.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/testReport/ |
| Max. process+thread count | 175 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/8/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-14 16:11 UTC, Reidddddd commented
Please fix the whitespace errors. @YutSean 
We could ignore the others, since jdk7 can't builld hbase-thrift module by now.
BTW, have you tested on your env? is the build successful on local? do failed unit tests pass?

2021-06-15 03:16 UTC, YutSean commented
We have built the project locally and it works normally in our production environment. We have run the unit tests under hbase-thrift and found no failure.

2021-06-15 04:04 UTC, Reidddddd commented
Please fix the whitespace warning

2021-06-15 07:35 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 59s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 47s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 56s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 10s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 19s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 53s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 53s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 43s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  1s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 45s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 57s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 34s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 66 unchanged - 38 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 30s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 28s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 28s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 38s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 20s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 55s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  The patch does not generate ASF License warnings.  |
|  |   |  47m 15s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 87e98dcb4fd5 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/testReport/ |
| Max. process+thread count | 181 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/9/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-15 11:02 UTC, Reidddddd requested changes

2021-06-15 11:02 UTC, Reidddddd commented on hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift/Hbase.thrift
> +}
Add a new line here.

2021-06-15 11:08 UTC, YutSean commented on hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift/Hbase.thrift
> +}
Fixed

2021-06-15 11:55 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 23s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 27s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 59s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 47s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  8s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 20s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 54s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 54s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 41s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 59s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 44s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 58s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 35s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 66 unchanged - 38 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 28s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 36s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 33s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 37s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 17s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 43s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  47m  5s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux a735605093ae 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/testReport/ |
| Max. process+thread count | 112 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/10/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-16 08:46 UTC, Reidddddd commented on hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThriftHBaseServiceHandler.java
> -  public void testConsistency() throws Exception {
why this method is deleted?

2021-06-16 08:47 UTC, Reidddddd commented on hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThriftHBaseServiceHandler.java
> +import static org.junit.Assert.fail;
are the import orders correct? looks like should be org.* then java.*

2021-06-16 08:49 UTC, Reidddddd commented on hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/ThriftServerRunner.java
> +class ThriftServerRunner extends Thread implements Closeable {
public?
missing annotation?

2021-06-16 08:52 UTC, Reidddddd commented on hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/ThriftServerRunner.java
> +  @Override public void run() {
newline between override and publice

2021-06-16 08:52 UTC, Reidddddd commented on hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/ThriftServerRunner.java
> +  @Override public void close() throws IOException {
ditto

2021-06-16 08:53 UTC, Reidddddd commented on hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftServerCmdLine.java
> - * Copyright The Apache Software Foundation
We should avoid changing the header

2021-06-16 08:56 UTC, Reidddddd commented on hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift2/hbase.thrift
> +  AND,
?

2021-06-16 08:57 UTC, Reidddddd commented on hbase-thrift/src/main/resources/hbase-webapps/thrift/thrift.jsp
> -      <tr>
why remove?

2021-06-16 08:57 UTC, Reidddddd commented on hbase-thrift/src/main/resources/hbase-webapps/static/js/jquery.min.js
> +(function(e,t){function _(e){var t=M[e]={};return v.each(e.split(y),function(e,n){t[n]=!0}),t}function H(e,n,r){if(r===t&&e.nodeType===1){var i="data-"+n.replace(P,"-$1").toLowerCase();r=e.getAttribu
newline?

2021-06-16 08:58 UTC, Reidddddd commented on hbase-thrift/src/main/resources/hbase-webapps/static/js/jquery.min.js
> +(function(e,t){function _(e){var t=M[e]={};return v.each(e.split(y),function(e,n){t[n]=!0}),t}function H(e,n,r){if(r===t&&e.nodeType===1){var i="data-"+n.replace(P,"-$1").toLowerCase();r=e.getAttribu
or is it generated?

2021-06-16 09:35 UTC, Reidddddd requested changes
style nits

2021-06-17 03:28 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  6s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 47s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 56s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 13s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 19s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 49s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 59s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 45s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 57s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 34s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 39 new + 68 unchanged - 36 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 31s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 48s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 30s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 41s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 24s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 38s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 36s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  The patch does not generate ASF License warnings.  |
|  |   |  46m 38s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux e80bca85523b 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/testReport/ |
| Max. process+thread count | 112 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/11/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-17 04:30 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m 56s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  7s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 49s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 59s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 10s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 19s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 10s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 50s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 11s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  1s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 44s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 58s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 36s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 44 new + 63 unchanged - 41 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 30s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 36s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   0m 12s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 48s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 30s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   3m 19s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 39s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 42s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 36s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 23s |  The patch does not generate ASF License warnings.  |
|  |   |  59m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux b07aedc08470 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/testReport/ |
| Max. process+thread count | 102 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/12/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-17 06:10 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 49s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  1s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 26s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 19s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m  2s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   1m  8s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 20s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 22s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  5s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 38s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 19s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 54s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 21s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 43s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  3s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   1m  3s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 16s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 46s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 44 new + 63 unchanged - 41 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 39s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 43s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m 29s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 37s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   4m  4s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   4m  4s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 57s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 40s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   |  56m 10s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux afcbd427d484 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/testReport/ |
| Max. process+thread count | 171 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/13/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-17 06:57 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 15s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  1s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 26s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 47s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 49s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 58s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 11s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 19s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 54s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 41s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  0s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 52s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 45s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 58s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 34s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 66 unchanged - 38 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 29s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 36s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 22s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 30s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 47s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 14s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 43s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 26s |  The patch does not generate ASF License warnings.  |
|  |   |  46m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 7e340bf64bba 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/testReport/ |
| Max. process+thread count | 130 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/14/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-17 07:20 UTC, YutSean commented on hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftServerCmdLine.java
> - * Copyright The Apache Software Foundation
Fixed

2021-06-18 12:42 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  8s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 49s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m 10s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 18s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 56s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 13s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 53s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m 17s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  4s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 48s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 48s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 57s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 35s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 44 new + 63 unchanged - 41 fixed = 107 total (was 104)  |
| -1 :x: |  checkstyle  |   0m 36s |  hbase-thrift: The patch generated 2 new + 82 unchanged - 77 fixed = 84 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 1 ill-formed XML file(s).  |
| -1 :x: |  shadedjars  |   0m 12s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 50s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 32s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   3m 20s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 36s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 45s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 37s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   |  48m 49s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | dev-support/hbase_eclipse_formatter.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense xml javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux e825992bfaaf 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / a40f458 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/diff-checkstyle-hbase-thrift.txt |
| xml | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/xml.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/testReport/ |
| Max. process+thread count | 171 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/15/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-21 02:45 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  1s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 29s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  9s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 48s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  9s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 20s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 53s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 40s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  0s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 53s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 46s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 46s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 57s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 34s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 66 unchanged - 38 fixed = 107 total (was 104)  |
| -1 :x: |  checkstyle  |   0m 35s |  hbase-thrift: The patch generated 2 new + 82 unchanged - 77 fixed = 84 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 1 ill-formed XML file(s).  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 30s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 43s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 19s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 43s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 36s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  47m 14s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | dev-support/hbase_eclipse_formatter.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense xml javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 2d723f2fed1c 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / 2e24bad |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/diff-checkstyle-hbase-thrift.txt |
| xml | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/xml.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/testReport/ |
| Max. process+thread count | 175 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/16/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-21 03:33 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  1s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 29s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  3s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 48s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 56s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  9s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 20s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 55s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 51s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 40s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  1s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 52s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 44s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 56s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 34s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 66 unchanged - 38 fixed = 107 total (was 104)  |
| -1 :x: |  checkstyle  |   0m 35s |  hbase-thrift: The patch generated 2 new + 82 unchanged - 77 fixed = 84 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 1 ill-formed XML file(s).  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 30s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 39s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 15s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 55s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 35s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   |  47m  6s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | dev-support/hbase_eclipse_formatter.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense xml javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux a338445af7df 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / 2e24bad |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/diff-checkstyle-hbase-thrift.txt |
| xml | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/xml.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/testReport/ |
| Max. process+thread count | 181 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/17/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-21 10:41 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  9s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +0 :ok: |  jshint  |   0m  0s |  jshint was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  1s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 9 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 27s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  3s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 50s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   0m 56s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   1m  9s |  branch-1 passed  |
| -1 :x: |  shadedjars  |   0m 19s |  branch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 54s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   1m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  2s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 49s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 44s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 57s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 34s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 41 new + 66 unchanged - 38 fixed = 107 total (was 104)  |
| +1 :green_heart: |  checkstyle  |   0m 29s |  The patch passed checkstyle in hbase-common  |
| +1 :green_heart: |  checkstyle  |   0m 36s |  hbase-thrift: The patch generated 0 new + 82 unchanged - 77 fixed = 82 total (was 159)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 1 ill-formed XML file(s).  |
| -1 :x: |  shadedjars  |   0m 13s |  patch has 7 errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 36s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   2m 48s |  hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| +1 :green_heart: |  findbugs  |   3m 31s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 43s |  hbase-common in the patch passed.  |
| -1 :x: |  unit  |   0m 37s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 25s |  The patch does not generate ASF License warnings.  |
|  |   |  47m 44s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | dev-support/hbase_eclipse_formatter.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2941 |
| JIRA Issue | HBASE-21674 |
| Optional Tests | dupname asflicense xml javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile jshint |
| uname | Linux 80bc926b1a66 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2941/out/precommit/personality/provided.sh |
| git revision | branch-1 / 5263b8c |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/branch-shadedjars.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/diff-compile-javac-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| xml | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/xml.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/diff-javadoc-javadoc-hbase-thrift-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/testReport/ |
| Max. process+thread count | 112 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2941/18/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-06-22 03:25 UTC, Reidddddd approved these changes
+1

2021-06-22 03:26 UTC, merged