HBASE-28468: Integration of time-based priority caching in eviction logic.
apache/hbase pull request #5826
Opened 2024-04-15 06:14 UTC by jhungund

HBASE-28468: Integration of time-based priority caching in eviction logic.

The time-based priority caching relies on the presence of file paths in the block-cache key.
However, in case of the persitent cache, the file paths are not persisted in the files.

Hence, when the region server is restarted, the block cache keys need to be
repopulated with the file paths.

This change addresses the following:
1. Always populate the block-cache key with path during its creation.
2. Fetch the file paths corresponding to the file names of the block-cache key
   during restarts.
3. Use the Data-Tiering-Manager APIs during cache-full scenario to evict the cold file blocks.

2024-04-15 09:09 UTC, wchevreuil requested changes
You are passing @vinayakphegde 's commit together with yours in this PR, and this is causing conflicts with the target branch (the PR can't be merged). Please rebase your local branch first, resolve any conflicts locally and force push to your branch, making sure the PR is mergeable.

2024-04-15 09:34 UTC, jhungund commented on hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketProtoUtils.java
> +      BlockCacheKey key;
Need handling with and without paths in the BlockCacheKey creation

2024-04-15 09:37 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   1m 24s |  Docker failed to build yetus/hbase:8a715fadd5.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/5826 |
| JIRA Issue | HBASE-28468 |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2024-04-15 09:46 UTC, jhungund commented
> You are passing @vinayakphegde 's commit together with yours in this PR, and this is causing conflicts with the target branch (the PR can't be merged). Please rebase your local branch first, resolve any conflicts locally and force push to your branch, making sure the PR is mergeable.

Ack!

2024-04-15 14:05 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 49s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  2s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ HBASE-28463 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  5s |  HBASE-28463 passed  |
| +1 :green_heart: |  compile  |   0m 51s |  HBASE-28463 passed  |
| +1 :green_heart: |  shadedjars  |   5m 17s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 27s |  HBASE-28463 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 49s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 13s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 26s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 243m  6s |  hbase-server in the patch failed.  |
|  |   | 269m 17s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5826 |
| JIRA Issue | HBASE-28468 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux ca34f533425f 5.4.0-172-generic #190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28463 / b7bb8b9d27 |
| Default Java | Eclipse Adoptium-11.0.17+8 |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/testReport/ |
| Max. process+thread count | 5087 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2024-04-15 14:07 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 26s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ HBASE-28463 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 47s |  HBASE-28463 passed  |
| +1 :green_heart: |  compile  |   0m 41s |  HBASE-28463 passed  |
| +1 :green_heart: |  shadedjars  |   5m 45s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 25s |  HBASE-28463 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 29s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 41s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 41s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 46s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 23s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 247m 40s |  hbase-server in the patch failed.  |
|  |   | 271m 56s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5826 |
| JIRA Issue | HBASE-28468 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux f1920bd54ea5 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28463 / b7bb8b9d27 |
| Default Java | Temurin-1.8.0_352-b08 |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/artifact/yetus-jdk8-hadoop3-check/output/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/testReport/ |
| Max. process+thread count | 4768 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5826/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2024-04-15 15:21 UTC, wchevreuil reviewed
Can we add a UT for the eviction logic? I can't see any test for that.

2024-04-15 15:21 UTC, wchevreuil commented on hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
> +
We can do like this here, but then can we think if we can modify DataTieringManager somehow to track when we have no CF with TIME_RANGE type? That way we could avoid this extra loops through the whole set of block keys unnecessarily.

Alternatively, we could follow the BucketEntryGroup logic starting from #987. We could define a COLD priority group and add that as the first group in the priority queue. That way we don't need this extra loop over the whole block sets to find out which blocks are cold. We would leverage the already existing loop from line #996 for that.

2024-04-16 07:31 UTC, jhungund commented on hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
> +              BlockCacheKey cacheKey = new BlockCacheKey(path, offset, true, BlockType.DATA);
The constructor used earlier(BlockCacheKey(name, offset);) sets these parameters internally. Hence, I used these parameters:

  public BlockCacheKey(String hfileName, long offset) {
    this(hfileName, offset, true, BlockType.DATA);
  }

2024-04-16 07:31 UTC, jhungund commented on hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketProtoUtils.java
> +      LOG.error("Error while getting DataTieringManager instance: {}", e.getMessage());
ack!

2024-04-18 15:10 UTC, wchevreuil commented
Can we close this PR and favour the #5829 as the solution for HBASE-28468?

2024-04-19 05:18 UTC, jhungund commented
> Can we close this PR and favour the #5829 as the solution for [HBASE-28468](https://issues.apache.org/jira/browse/HBASE-28468)?

ack!

2024-04-19 05:18 UTC, closed without merging

2024-04-19 05:19 UTC, jhungund commented
Closing this PR in favour of https://github.com/apache/hbase/pull/5829 as the solution for [HBASE-28468](https://issues.apache.org/jira/browse/HBASE-28468)?